name: Add File

on:
  push:
    branches:
      - main

jobs:
  add_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add file
        run: |
          echo "Your file content" > new_file.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add new_file.txt
          git commit -m "Add new file via GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
