name: Inatial Setup

on:
  push:
    branches:
      - main

jobs:
  inatial-setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Adding README to the repository.
        run: |
          echo "Your file content" > README.md
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Add new file via GitHub Actions"
          git push origin main
      - name: Adding topic to the repository.
        run: |
          gh api \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/glg/${{ github.repository }}/topics \
            -f "names[]=sam-monorepo" -f "names[]=sam"